Add assert builder
blackfireio/php-sdk pull request #60
Opened 2021-09-16 18:50 UTC by pashak09

I think it would be nice to be able to set asserts using methods such as:
```
->sqlQueriesCountGreaterThanOrEqual(3)
->httpRequestsCountEquals(1)
```

In this PR I have implemented some of this functionality, if you think that this is a good idea that is worthy of attention, let me know, I will try to add an implementation for all possible assertions.

Usage example:
```
$configuration = new Configuration();
$assertBuilder = $configuration->getAssertBuilder();
$assertBuilder
    ->sqlQueriesCountGreaterThanOrEqual(1, 'test')
    ->httpRequestsCountEquals(1);
```
At the moment I have implemented the following assertions:
```
 for sql
 sqlQueriesCountGreaterThanOrEqual(int $expected, string|null $name = null)
 sqlQueriesCountLessThanOrEqual(int $expected, string|null $name = null)
 sqlQueriesCountGreaterThan(int $expected, string|null $name = null)
 sqlQueriesCountCountLessThan(int $expected, string|null $name = null)
 sqlQueriesCountNotEquals(int $expected, string|null $name = null)
 sqlQueriesCountEquals(int $expected, string|null $name = null)
 for http
 httpRequestsCountGreaterThanOrEqual(int $expected, string|null $name = null)
 httpRequestsCountLessThanOrEqual(int $expected, string|null $name = null)
 httpRequestsCountGreaterThan(int $expected, string|null $name = null)
 httpRequestsCountCountLessThan(int $expected, string|null $name = null)
 httpRequestsCountNotEquals(int $expected, string|null $name = null)
 httpRequestsCountEquals(int $expected, string|null $name = null)
```

2021-09-17 07:31 UTC, jderusse commented on src/Blackfire/Profile/AssertManager.php
> +class AssertManager
"Manager" is too generic, and gives the feeling it performs some kind of business logic. While it's only an array
```
class AssertionsList // or AssertionsCollection or AssertionsStack
{
  public function add() {}
  public function list() {}
}
```

2021-09-17 07:31 UTC, jderusse commented on src/Blackfire/Profile/Configuration.php
> +        $this->assertManager = new AssertManager();
What's about allowing people injecting their own instance?

```suggestion
    public function __construct($manager)
    {
        $this->assertManager = $manager ? $manager : new AssertManager();
```

2021-09-17 07:31 UTC, jderusse commented on src/Blackfire/Profile/AssertBuilder.php
> +    public function __call($functionName, $arguments)
I'm mix feeling about thing magic `__call` method.
The method is complex, and this magic method prevents people browsing the source code. 
I'd rather write all the methods (like PhpUnit do with the tens of assertXXX functions)

2021-09-17 07:31 UTC, jderusse commented on src/Blackfire/Profile/AssertBuilder.php
> +    const COMPARISON_OPERATORS_MAP = [
I'm not sure this works with our minimum PHP version

2021-09-17 07:33 UTC, lolautruche requested changes

2021-09-17 07:33 UTC, lolautruche commented on src/Blackfire/Profile/AssertBuilder.php
> +        if (!$methodName) {
```suggestion
        if ('' === $methodName) {
```

2021-09-17 07:33 UTC, lolautruche commented on src/Blackfire/Profile/AssertManager.php
> +    private $assertions;
```suggestion
    private $assertions = [];
```

2021-09-17 07:33 UTC, lolautruche commented on src/Blackfire/Profile/Configuration.php
> +        return (bool) $this->assertManager->getAssertions();
I'd rather add a `hasAssertions()` method to the assert manager.
I'd also avoid the transtyping in the new method:

```php
public function hasAssertions()
{
    return !empty($this->assertions);
}
```

2021-09-17 07:33 UTC, lolautruche commented on src/Blackfire/Profile/Configuration.php
```suggestion
        if (!$this->hasAssertions && !$this->metrics) {
            return;
        }

        $assertions = $this->assertManager->getAssertions();
```

2021-09-17 07:33 UTC, lolautruche commented on src/Blackfire/Profile/Configuration.php
> +        if ($assertions) {
With the change suggested above, the condition check is not needed anymore

2021-09-17 07:33 UTC, lolautruche commented on src/Blackfire/Profile/Configuration.php
> +        return new AssertBuilder($this->assertManager);
Liskov substitution principle violation here 😉 .
Unless, there is a good reason to create a new `AssertBuilder` object everytime this method is called

2021-09-17 07:34 UTC, lolautruche commented on src/Blackfire/Profile/Configuration.php
> +        $this->assertManager = new AssertManager();
```php
public function __construct($manager = null)
```

And it could be type-hinted as well

2021-09-17 07:34 UTC, lolautruche commented on src/Blackfire/Profile/AssertBuilder.php
> +    public function __call($functionName, $arguments)
Agreed

2021-09-20 07:36 UTC, lolautruche approved these changes

2021-09-27 09:36 UTC, jderusse reviewed
Small comment.

I don't think we need theses interfaces

2021-09-27 09:36 UTC, jderusse commented on src/Blackfire/Profile/Assertion/AssertionsBuilder.php
> +    const LESS_THAN_OR_EQUAL_OPERATOR = '<=';
I'm not sure we need public const for this

2021-09-27 09:36 UTC, jderusse commented on src/Blackfire/Profile/Assertion/AssertionsBuilderInterface.php
> +interface AssertionsBuilderInterface
I'm not sure we need an interface for this. 
This PR provides only one implementation of this interface and I'm not sure someone would provide something else.

2021-09-27 09:36 UTC, jderusse commented on src/Blackfire/Profile/Assertion/AssertionsCollectionInterface.php
> +interface AssertionsCollectionInterface
same here

2021-09-27 18:47 UTC, pashak09 commented on src/Blackfire/Profile/Assertion/AssertionsBuilder.php
> +    const LESS_THAN_OR_EQUAL_OPERATOR = '<=';
![image](https://user-images.githubusercontent.com/37300581/134967273-946bf9cd-decf-4438-a57c-62e638c50296.png)

2021-09-27 20:49 UTC, jderusse commented on src/Blackfire/Profile/Assertion/AssertionsBuilder.php
> +    const LESS_THAN_OR_EQUAL_OPERATOR = '<=';
sorry for my previous comment. I mean, I don't think we need these constant.
When can hardcode `<=`, `>`, etc directly in the assertion

2021-09-28 20:38 UTC, jderusse approved these changes

2021-09-29 07:20 UTC, lolautruche approved these changes

2023-04-01 13:01 UTC, closed without merging